server:
  port: 8090

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis-rate-limiter
      port: 6379

  cloud:
    gateway:
      routes:
        - id: msvc-suscriptions
          uri: lb://msvc-suscriptions
          predicates:
            - Path=/api/suscriptions/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter: 
                replenishRate: 3 # Cantidad de peticiones por minuto aceptadas
                burstCapacity: 10 # Cantidad de peticiones acumuladas
              key-resolver: "#{@userKeyResolver}" # El bean de configuracion


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka



