server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: suscriptions
          uri: lb://msvc-suscribtions
          predicates:
            - Path=/api/suscriptions/**

          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



