server:
  port: 9090

spring:
  application:
    name: api-gateway-teenants
  datasource:
    url: jdbc:postgresql://postgres-teenants:5432/s
    username: admin
    password: PASSWORD

  data:
    redis:
      host: redis-rl
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761


app:
  admin:
    secret-token: AV4DAEDITH3R3Y0URS3CRETT0K3N45FS