server:
  port: 9001

spring:
  application:
    name: msvc-suscriptions

  datasource:
    url: jdbc:postgresql://postgres-suscriptions:5432/suscriptions-db
    username: admin
    password: s3cur3p4SSw0rd


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-ds:8761


