server:
  port: 9002

spring:
  application:
    name: msvc-email

  mail:
    host: smtp.gmail.com
    port: 587
    username: kylebutler1033@gmail.com
    password: "aqvq tldh caef qwsr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000ms 

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


      