server:
  port: 9002

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kylebutler1033@gmail.com
    password: "aqvq tldh caef qwsr"
    mail.smtp.auth: true 
    mail.smtp.starttls.enable: true
    

  application:
    name: msvc-email

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

